image::https://github.com/spring-io/autoln/workflows/CI/badge.svg[Build Status,link=https://github.com/spring-io/autoln/actions]

= autoln

The autoln script keeps symbolic links to a project's docs and/or schemas to be kept up to date.
For example, if the latest build of Spring Framework is https://docs.spring.io/spring-framework/docs/5.2.9.RELEASE/spring-framework-reference/[5.2.9.RELEASE] it makes it easier for users to refer to the docs using a symlink of https://docs.spring.io/spring-framework/docs/current/spring-framework-reference/[current] and https://docs.spring.io/spring-framework/docs/5.2.x/spring-framework-reference/[5.2.x].
When the Spring 5.2.9.RELEASE release is performed, the autoln script can ensure the links are automatically updated so users do not need to update bookmarks.

== autoln generated links

Below is a list of supported symbolic links that are generated when using autoln.
The links can be enabled for a project's docs and/or schema.

* `current` the latest stable build. This is defined as the largest version number ending in `.RELEASE` or not ending in a number.
* `current-SNAPSHOT` the most recent snapshot. This is defined as the largest version number ending in `CI-SNAPSHOT`, `BUILD-SNAPSHOT`, or `-SNAPSHOT`.
* `<major>.<minor>.x` the most recently released version starting with `<major>.<minor>`.
This reference can refer to a milestone build (in the event there are no builds that end in `.RELEASE` or a number), but will not refer to a snapshot.
For example, to get the most recently released version of 5.2, one could use the link `5.2.x`.
* `<major>.<minor>.x-SNAPSHOT` the most recent snapshot starting with `<major>.<minor>`.
For example, to get the most recently snapshot of 5.2, one could use the link `5.2.x-SNAPSHOT`.

If a project uses a different naming convention, then a one-time link pointing to the links updated by the autorepo script can be created.
For example, if the project uses ga instead of current, a link named ga pointing to current could be created.

== Previewing autoln

Since autoln impacts released resources it is best to preview what autoln will do before <<Activating autoln>> it on a particular project.
This can be done by logging onto docs.spring.io and running autoln.

<pre><code>$ cd /var/www/domains/springsource.org/static/autorepo_script
$ php testlinks.php
...
Link Deleted: /opt/s2/ers/servers/static.springsource.org/htdocs/autorepo/docs/spring-framework/1.1.x
Link Created: cd /opt/s2/ers/servers/static.springsource.org/htdocs/autorepo/docs/spring-framework/; ln -fs 1.1.5 1.1.x
...
</code></pre>

Of course not all of these actions are being performed by the autoln process, because each project needs to [activate](autorepo-version-updating#Activating-autoln) the autoln script. However, it gives developers the knowledge of what would happen if they did opt in. The output from the test script can be a bit much, but the results can be filtered with relative ease. For example, to view only the Spring Integration results with relative paths using the following command:

<pre><code>$ php testlinks.php | grep /spring-integration/ | sed 's/\/.*autorepo\///'
Link Deleted: docs/spring-integration/2.1.x
Link Created: cd docs/spring-integration/; ln -fs 2.1.3.RELEASE 2.1.x
Link Created: cd docs/spring-integration/; ln -fs 2.1.4.BUILD-SNAPSHOT 2.1.x-SNAPSHOT
Link Created: cd docs/spring-integration/; ln -fs 2.2.0.BUILD-SNAPSHOT current-SNAPSHOT
Link Created: cd docs/spring-integration/; ln -fs 2.1.3.RELEASE current
...
</code></pre>

Be careful to ensure that the filtering matches the entire project as some projects use different directory names for docs and schemas. For example, Spring Framework uses schema/spring and docs/spring-framework. If this is the case, ensure to update the command appropriately. For example:

<pre><code>$ php testlinks.php | grep -E /spring\(/\|-framework\) | sed 's/\/.*autorepo\///'</code></pre>

